In [8]:
print("this is python")

this is python


# This is markdown

## this is sample code

this is third heading

In [9]:
print("this is python")

this is python


In [17]:
! pip install numpy

  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)


In [1]:
import numpy as np

initialize the array with the help of numpy

In [2]:


arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [3]:
arr = arr*2
print(arr)

[2 4 6]


In [4]:
arr.shape

(3,)

In [6]:
arr1 =np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr1)
arr1.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)